### PR TITLE
fix deprecated stuff

### PR DESCRIPTION
**Pull request by narimiran**

### CODE REVIEW

**Comment by Vladar4** [comment]
Already fixed in `devel` branch: https://github.com/Vladar4/nimgame2/commit/a0af414d2e51345394e8fa8b6301bacad566491e#diff-cdb07207a519ef4c7003f883c113dc5bL467

**Comment by narimiran** [comment]
Any idea when `devel` might get merged into `master`?

**Comment by Vladar4** [comment]
Hopefully, soon enough,
when I'll get some time to finish a couple of new features.

**Comment by narimiran** [comment]
> Hopefully, soon enough

Ok, I'm asking because this small stuff I changed in this PR is blocking me from deleting the deprecated `random` from stdlib.

So if it will take you some time to finish those other features, I would appreciate if this could get merged in the mean time. (Otherwise we'll have to disable testing this repo until this is fixed, and I'd rather not do that)

**Comment by Vladar4** [comment]
Ah, sure, please see if 9c37148d574b8c04ec82327972be05a297907103 helps.

**Pull request closed without merging**
