### PR TITLE
Sprite copy fix

### PR DESCRIPTION
**Pull request by CodeDoes**
entity.copy() didn't work for me until I added this line

### CODE REVIEW

**Comment by Vladar4** [comment]
It looks like you are trying to merge into the master branch instead of devel one.

**Comment by CodeDoes** [comment]
Is it better now? Thanks for the patience

**Comment by Vladar4** [comment]
Commit looks good, but github don't let me reopen the pull request after the branch was "force-pushed or recreated". Looks like a similar issue: https://gist.github.com/robertpainsi/2c42c15f1ce6dab03a0675348edd4e2c

**Comment by CodeDoes** [comment]
Can't you fix on your end. this is way too much hassle for one line lol.

**Comment by Vladar4** [comment]
OK, implemented in f97bc58c462a346eeeef2620c9f913b1f180a3d9

**Pull request closed without merging**
